-- 1. Add ownership column to tracks
ALTER TABLE public.tracks 
ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid();

-- 2. Create profiles table
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) PRIMARY KEY,
  username TEXT UNIQUE,
  avatar_url TEXT,
  role TEXT DEFAULT 'user' -- 'admin' or 'user'
);

-- Enable RLS on Profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public profiles are viewable by everyone" ON public.profiles;
CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- 3. Create Votes Table
CREATE TABLE IF NOT EXISTS public.votes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  track_id TEXT REFERENCES public.tracks(tile_id) ON DELETE CASCADE NOT NULL,
  vote_type INT CHECK (vote_type IN (1, -1)), -- 1 for upvote, -1 for downvote
  UNIQUE(user_id, track_id) -- Prevents one user voting twice on one track
);

ALTER TABLE public.votes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public votes are viewable by everyone" ON public.votes FOR SELECT USING (true);
CREATE POLICY "Users can insert their own votes" ON public.votes FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own votes" ON public.votes FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own votes" ON public.votes FOR DELETE USING (auth.uid() = user_id);

-- 4. Update Tracks RLS (Godmode Transition)
-- Drop old policies
DROP POLICY IF EXISTS "godmode_delete" ON public.tracks;
DROP POLICY IF EXISTS "public_upload" ON public.tracks; -- Replaced by authenticated upload

-- New Policies
CREATE POLICY "Owners can delete their own tracks" ON public.tracks FOR DELETE USING (auth.uid() = user_id);

-- Admin Policy (Check profiles for role='admin')
CREATE POLICY "Admins can delete anything" ON public.tracks FOR DELETE USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Authenticated Upload Policy
CREATE POLICY "Authenticated users can upload" ON public.tracks FOR INSERT TO authenticated 
WITH CHECK (auth.uid() = user_id);

-- Allow updates by owner
CREATE POLICY "Owners can update their own tracks" ON public.tracks FOR UPDATE USING (auth.uid() = user_id);
